name: Dummy Action to keep action alive
on:
  schedule:
    - cron: "0 0 */14 * *"   # 每 14 天
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p .github
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .github/.keepalive
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/.keepalive
          git commit -m "chore: keepalive" || echo "no changes"
          git push
